print("Son, you're in big trouble")
print("WHY?")
print("Because you're texting me while your in school")
print("Are you serious?!! You texted me first!")
print()
print("What does IDK, LY & TTYL mean?")
print("I don't know, love you, talk to you later")
print("OK, I will ask your sister")
print()
print("Dad there's a moth on the outside of the bathroom door can you get rid of it?")
print("Pls hurry because I'm going to cry")
print("Dad")
print("Dad")
print("Dad is dead. You're next. love, moth")