a1=input("a number: ")
a2=input("a measurement of time: ")
a3=input("a motor vehicle: ")
a4=input("adjective: ")
a5=input("adjective: ")
a6=input("noun(plural): ")
a7=input("colour: ")
a8=input("body part: ")
a9=input("verb: ")
a10=input("number: ")
a11=input("noun (plural): ")
a12=input("noun: ")
a13=input("part of the body: ")
a14=input("verb: ")
a15=input("noun: ")
a16=input("adjective: ")
a17=input("silly word: ")
a18=input("noun: ")
print(f"It was about {a1} {a2} ago when I came to the hospital in a {a3}.")
print(f"The hospital is a/an {a4} place, there are a lot of {a5} {a6} here.")
print(f"There are nurses here who have {a7} {a8}.")
print(f" If someone wants to come into my room I told them that they have to {a9} first.")
print(f"I have decorated my room with {a10} {a11}.")
print(f"Today a doctor came into my room and they were wearing a {a12} on their {a13}.")
print(f"I heard that all doctors {a14} {a15} every day for breakfast.")
print(f"The most {a16} thing about being in the hospital is the {a17} {a18}!")